[extend]
useDefault = true

[allowlist]
paths = [
  '''(^|/)node_modules/''',
  '''(^|/)vendor/''',
  '''(^|/)dist/''',
  '''(^|/)coverage/''',
  '''(^|/)back-end/seeder/''',
  '''(^|/)back-end/runtime/''',
  '''(^|/)cache/''',
  '''(^|/)logs/''',
  '''(^|/)storage/''',
  '''(^|/)uploads/''',
  '''language-pack.*\.json$''',
  '''(^|/)package-lock\.json$''',
  '''(^|/)composer\.lock$''',
]
